apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 324619539895.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 324619539895.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: 9bc2f45b
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
